from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional


CATALOG_VERSION = "v1"


HELP_PAGES: List[Dict[str, str]] = [
    {"pageKey": "getting-started", "label": "Getting Started", "description": "How PropertyLens organizes property data, sources, and calculations."},
    {"pageKey": "summary", "label": "Property Summary", "description": "Property-level value, equity, return, and cash-flow metrics."},
    {"pageKey": "loans", "label": "Loans", "description": "Loan balances, payments, amortization, reconciliation, and payoff scenarios."},
    {"pageKey": "rental", "label": "Rental", "description": "Rental income, occupancy, vacancy, rent growth, and rental performance."},
    {"pageKey": "expenses", "label": "Expenses", "description": "Operating expenses, capital expenses, source precedence, and trends."},
    {"pageKey": "taxes", "label": "Taxes", "description": "Schedule E, tax summaries, taxable income, and filed reconciliation."},
    {"pageKey": "depreciation", "label": "Depreciation", "description": "Cost basis, land exclusion, assets, partial-year rules, and remaining basis."},
    {"pageKey": "scenarios", "label": "Scenarios", "description": "What-if assumptions for payoff, sale, refinance, rent, and return models."},
    {"pageKey": "portfolio", "label": "Portfolio Metrics", "description": "Portfolio totals and weighted ratios across included properties."},
    {"pageKey": "documents", "label": "Documents and Data Sources", "description": "Source labels, source priority, imports, and provenance."},
    {"pageKey": "reconciliation", "label": "Reconciliation", "description": "How accepted sources are compared and issue statuses are explained."},
    {"pageKey": "conventions", "label": "Calculation Conventions", "description": "System-wide rules for rounding, dates, missing values, partial years, and duplicates."},
]


def _input(key: str, label: str, definition: str, data_type: str = "currency") -> Dict[str, str]:
    return {"key": key, "label": label, "definition": definition, "dataType": data_type}


def _formula(
    metric_key: str,
    page_key: str,
    section_key: str,
    name: str,
    short_definition: str,
    formula_lines: Iterable[str],
    inputs: Iterable[Dict[str, str]],
    *,
    detailed_definition: Optional[str] = None,
    example: Optional[Dict[str, Any]] = None,
    source_priority: Optional[List[str]] = None,
    source_type: str = "calculated",
    assumptions: Optional[List[str]] = None,
    exclusions: Optional[List[str]] = None,
    related: Optional[List[str]] = None,
    display_format: Optional[str] = None,
    calculation_frequency: str = "On backend engine rebuild or source update",
    search_terms: Optional[List[str]] = None,
) -> Dict[str, Any]:
    lines = list(formula_lines)
    return {
        "metricKey": metric_key,
        "formulaDefinitionId": f"{metric_key}:{CATALOG_VERSION}",
        "pageKey": page_key,
        "sectionKey": section_key,
        "name": name,
        "shortDefinition": short_definition,
        "detailedDefinition": detailed_definition,
        "formula": "\n".join(lines),
        "formulaLines": lines,
        "inputDefinitions": list(inputs),
        "example": example,
        "sourcePriority": source_priority or [],
        "sourceType": source_type,
        "assumptions": assumptions or [],
        "exclusions": exclusions or [],
        "relatedMetricKeys": related or [],
        "displayFormat": display_format,
        "calculationFrequency": calculation_frequency,
        "version": CATALOG_VERSION,
        "searchTerms": search_terms or [],
    }


FORMULA_DEFINITIONS: List[Dict[str, Any]] = [
    _formula(
        "property.current_market_value", "summary", "property-value", "Current Market Value",
        "The latest accepted estimate of the property's current value.",
        ["Latest accepted property valuation = Current Market Value"],
        [_input("market_value", "Market value", "Accepted property valuation or fallback value.")],
        source_priority=["User-accepted valuation", "Appraisal", "External valuation source", "Imported property document", "Purchase price when no newer value exists"],
        source_type="mixed",
        assumptions=["This is normally sourced, not calculated."],
        display_format="currency",
        search_terms=["value", "valuation", "market"],
    ),
    _formula(
        "property.current_equity", "summary", "equity", "Current Equity",
        "The ownership value remaining after active loan balances are subtracted from market value.",
        ["Current Market Value", "− Sum of Active Loan Balances", "= Current Equity"],
        [_input("current_market_value", "Current Market Value", "Latest accepted value."), _input("active_loan_balance", "Active Loan Balances", "Sum of current balances for open loans.")],
        source_type="calculated",
        exclusions=["Future selling costs are excluded unless a metric is explicitly named Net Sale Equity."],
        related=["property.equity_percentage", "loan.loan_to_value"],
        display_format="currency",
    ),
    _formula(
        "property.equity_percentage", "summary", "equity", "Equity Percentage",
        "Current equity as a percentage of current market value.",
        ["Current Equity", "÷ Current Market Value", "× 100", "= Equity Percentage"],
        [_input("current_equity", "Current Equity", "Backend-calculated equity."), _input("current_market_value", "Current Market Value", "Latest accepted value.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "property.gross_appreciation", "summary", "appreciation", "Gross Appreciation",
        "The change between current market value and purchase price.",
        ["Current Market Value", "− Purchase Price", "= Gross Appreciation"],
        [_input("current_market_value", "Current Market Value", "Latest accepted value."), _input("purchase_price", "Purchase Price", "Accepted acquisition price.")],
        source_type="calculated",
        related=["property.appreciation_percentage", "property.annualized_appreciation"],
        display_format="currency",
    ),
    _formula(
        "property.appreciation_percentage", "summary", "appreciation", "Appreciation Percentage",
        "Gross appreciation relative to purchase price.",
        ["Gross Appreciation", "÷ Purchase Price", "× 100", "= Appreciation Percentage"],
        [_input("gross_appreciation", "Gross Appreciation", "Value increase or decrease."), _input("purchase_price", "Purchase Price", "Accepted acquisition price.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "property.annualized_appreciation", "summary", "appreciation", "Annualized Appreciation",
        "Compounded annual growth rate between purchase price and current market value.",
        ["(Current Market Value ÷ Purchase Price)^(1 ÷ Years Owned)", "− 1", "= Annualized Appreciation Rate"],
        [_input("current_market_value", "Current Market Value", "Latest accepted value."), _input("purchase_price", "Purchase Price", "Accepted acquisition price."), _input("years_owned", "Years Owned", "Elapsed ownership duration.", "duration")],
        source_type="calculated",
        assumptions=["This is a compounded annual growth rate."],
        display_format="percentage",
    ),
    _formula(
        "property.monthly_cash_flow", "summary", "cash-flow", "Monthly Cash Flow",
        "Average monthly net cash flow after operating expenses and principal-and-interest debt service.",
        ["Annual Cash Flow", "÷ 12", "= Monthly Net Cash Flow"],
        [_input("annual_cash_flow", "Annual Cash Flow", "Backend annual cash-flow metric.")],
        source_type="calculated",
        assumptions=["The current backend summary derives monthly cash flow from annual cash flow divided by 12."],
        related=["property.annual_cash_flow", "property.noi", "loan.debt_service"],
        display_format="currency / month",
    ),
    _formula(
        "property.annual_cash_flow", "summary", "cash-flow", "Annual Cash Flow",
        "Annual operating income after principal-and-interest debt service.",
        ["Annual NOI", "− Annual Debt Service", "= Annual Net Cash Flow"],
        [_input("noi", "Annual NOI", "Net operating income."), _input("annual_debt_service", "Annual Debt Service", "Annual principal and interest debt service.")],
        example={"inputs": [{"label": "NOI", "display": "$34,692"}, {"label": "Annual debt service", "display": "$32,470"}], "computation": "$34,692 − $32,470", "result": "$2,222 annual cash flow"},
        source_type="calculated",
        exclusions=["Depreciation and income tax are excluded from cash flow."],
        display_format="currency / year",
    ),
    _formula(
        "property.noi", "summary", "income", "Net Operating Income",
        "Income generated by the property before financing costs, income taxes, and depreciation.",
        ["Gross Rental Income", "+ Other Property Income", "− Operating Expenses", "= Net Operating Income"],
        [_input("gross_rental_income", "Gross Rental Income", "Accepted rent for the period."), _input("other_property_income", "Other Property Income", "Accepted non-rent property income."), _input("operating_expenses", "Operating Expenses", "Backend-resolved operating expenses.")],
        example={"inputs": [{"label": "Rent", "display": "$38,400"}, {"label": "Other income", "display": "$600"}, {"label": "Operating expenses", "display": "$11,250"}], "computation": "$38,400 + $600 − $11,250", "result": "$27,750 NOI"},
        source_type="calculated",
        exclusions=["Mortgage principal", "Mortgage interest", "Depreciation", "Income taxes", "Capital expenditures unless a backend metric explicitly includes them"],
        related=["property.cap_rate", "portfolio.noi"],
        display_format="currency / year",
    ),
    _formula(
        "property.cap_rate", "summary", "returns", "Cap Rate",
        "Unlevered yield based on annual NOI and current market value.",
        ["Annual NOI", "÷ Current Market Value", "× 100", "= Cap Rate"],
        [_input("noi", "Annual NOI", "Net operating income."), _input("current_market_value", "Current Market Value", "Latest accepted value.")],
        source_type="calculated",
        related=["property.cost_basis_cap_rate", "property.noi"],
        display_format="percentage",
    ),
    _formula(
        "property.cost_basis_cap_rate", "summary", "returns", "Cost Basis Cap Rate",
        "Unlevered yield based on purchase price instead of current value.",
        ["Annual NOI", "÷ Purchase Price", "× 100", "= Cost Basis Cap Rate"],
        [_input("noi", "Annual NOI", "Net operating income."), _input("purchase_price", "Purchase Price", "Accepted acquisition price.")],
        source_type="calculated",
        assumptions=["Do not mix current-value cap rate and purchase-price cap rate without clear labels."],
        display_format="percentage",
    ),
    _formula(
        "property.cash_on_cash_return", "summary", "returns", "Cash-on-Cash Return",
        "Annual pre-tax cash flow divided by total cash invested.",
        ["Annual Pre-Tax Cash Flow", "÷ Total Cash Invested", "× 100", "= Cash-on-Cash Return"],
        [_input("annual_cash_flow", "Annual Pre-Tax Cash Flow", "Annual cash flow before income tax."), _input("cash_invested", "Total Cash Invested", "Backend-selected cash investment inputs.")],
        source_type="calculated",
        assumptions=["Backend cash invested currently includes accepted down payment and closing-cost inputs where available."],
        display_format="percentage",
    ),
    _formula(
        "property.total_return", "summary", "returns", "Total Return",
        "Economic return before income tax from cash flow, principal paydown, and appreciation components.",
        ["Net Cash Flow", "+ Principal Paid", "+ Unrealized Appreciation", "− Selling Costs, when included", "= Total Economic Return"],
        [_input("cash_flow", "Net Cash Flow", "Accepted cash-flow component."), _input("principal_paid", "Principal Paid", "Accepted or calculated principal reduction."), _input("appreciation", "Unrealized Appreciation", "Change in property value."), _input("selling_costs", "Selling Costs", "Included only by metrics that explicitly say so.")],
        source_type="mixed",
        exclusions=["Tax benefits are excluded unless the metric explicitly says After-Tax Total Return."],
        display_format="currency",
    ),
    _formula(
        "property.leveraged_return", "summary", "returns", "Leveraged Return",
        "Total economic return divided by initial cash invested.",
        ["Total Economic Return", "÷ Initial Cash Invested", "× 100", "= Leveraged Return"],
        [_input("total_return", "Total Economic Return", "Return components selected by the backend."), _input("initial_cash_invested", "Initial Cash Invested", "Backend-selected initial cash inputs.")],
        source_type="calculated",
        assumptions=["Leverage magnifies both gains and losses."],
        display_format="percentage",
    ),
    _formula(
        "loan.original_amount", "loans", "loan-summary", "Original Loan Amount",
        "The principal borrowed when the loan originated.",
        ["Reported loan principal at origination = Original Loan Amount"],
        [_input("original_amount", "Original Amount", "Accepted loan origination principal.")],
        source_priority=["Closing disclosure", "Mortgage statement", "Manual loan entry"],
        source_type="reported",
        display_format="currency",
    ),
    _formula(
        "loan.current_balance", "loans", "loan-summary", "Current Loan Balance",
        "The latest accepted outstanding principal balance for a loan.",
        ["Latest accepted balance source = Current Loan Balance"],
        [_input("current_balance", "Current Balance", "Accepted current principal balance.")],
        source_priority=["Accepted latest mortgage statement", "Accepted year-end statement", "Accepted Form 1098 outstanding principal", "Calculated amortization balance", "Manual correction"],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "loan.principal_paid", "loans", "amortization", "Principal Paid",
        "Principal reduction over the selected period.",
        ["Original Loan Amount − Current Loan Balance = Lifetime Principal Paid", "Opening Balance − Ending Balance + Principal-Increasing Adjustments − Principal-Decreasing Corrections = Period Principal Paid"],
        [_input("original_amount", "Original Loan Amount", "Loan origination principal."), _input("current_balance", "Current Loan Balance", "Latest accepted balance."), _input("opening_balance", "Opening Balance", "Period opening balance."), _input("ending_balance", "Ending Balance", "Period ending balance.")],
        source_type="mixed",
        assumptions=["Negative reconciliation results are not hidden with absolute values."],
        display_format="currency",
    ),
    _formula(
        "loan.loan_paid_percentage", "loans", "loan-summary", "Loan Paid Percentage",
        "The percentage of original loan principal that has been paid down.",
        ["Lifetime Principal Paid", "÷ Original Loan Amount", "× 100", "= Loan Paid Percentage"],
        [_input("principal_paid", "Lifetime Principal Paid", "Original amount minus current balance."), _input("original_amount", "Original Loan Amount", "Loan origination principal.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "loan.remaining_percentage", "loans", "loan-summary", "Remaining Loan Percentage",
        "The percentage of original loan principal that remains outstanding.",
        ["Current Loan Balance", "÷ Original Loan Amount", "× 100", "= Remaining Loan Percentage"],
        [_input("current_balance", "Current Loan Balance", "Latest accepted balance."), _input("original_amount", "Original Loan Amount", "Loan origination principal.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "loan.loan_to_value", "loans", "loan-summary", "Loan-to-Value",
        "Active loan balance as a percentage of current market value.",
        ["Total Active Loan Balance", "÷ Current Market Value", "× 100", "= LTV"],
        [_input("active_loan_balance", "Active Loan Balance", "Sum of active current balances."), _input("current_market_value", "Current Market Value", "Latest accepted value.")],
        source_type="calculated",
        assumptions=["Property-level debt metrics use the sum of all active loan balances."],
        display_format="percentage",
    ),
    _formula(
        "loan.monthly_principal_interest", "loans", "monthly-payment", "Monthly Principal and Interest Payment",
        "Scheduled monthly payment for principal and interest, excluding escrow and fees.",
        ["M = P × [r(1+r)^n] ÷ [(1+r)^n − 1]", "r = Annual Interest Rate ÷ 12"],
        [_input("principal", "P: Principal", "Loan principal."), _input("monthly_rate", "r: Monthly Interest Rate", "Annual interest rate divided by 12.", "percentage"), _input("term_months", "n: Payment Count", "Total scheduled monthly payments.", "integer")],
        source_type="calculated",
        exclusions=["Escrow", "Taxes", "Insurance", "HOA", "Fees"],
        display_format="currency / month",
    ),
    _formula(
        "loan.monthly_interest", "loans", "amortization", "Monthly Interest",
        "Interest charged for a month based on beginning monthly balance.",
        ["Beginning Monthly Balance", "× Monthly Interest Rate", "= Monthly Interest"],
        [_input("beginning_balance", "Beginning Monthly Balance", "Balance before the monthly payment."), _input("monthly_rate", "Monthly Interest Rate", "Annual interest rate divided by 12.", "percentage")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "loan.monthly_principal", "loans", "amortization", "Monthly Principal",
        "Scheduled principal portion of the monthly principal-and-interest payment.",
        ["Scheduled Principal and Interest Payment", "− Monthly Interest", "= Scheduled Monthly Principal"],
        [_input("monthly_pi", "Scheduled P&I", "Principal-and-interest payment."), _input("monthly_interest", "Monthly Interest", "Interest portion for the month.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "loan.ending_monthly_balance", "loans", "amortization", "Ending Monthly Balance",
        "Loan balance after scheduled and extra principal are applied.",
        ["Beginning Monthly Balance", "− Scheduled Principal", "− Extra Principal", "+ Principal-Increasing Adjustments", "= Ending Monthly Balance"],
        [_input("beginning_balance", "Beginning Monthly Balance", "Balance before payment."), _input("scheduled_principal", "Scheduled Principal", "Principal required by amortization."), _input("extra_principal", "Extra Principal", "Additional principal accepted by backend.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "loan.annual_interest_paid", "loans", "yearly-reconciliation", "Annual Interest Paid",
        "Interest paid for a loan during a year.",
        ["Sum of Accepted Monthly Interest Payments", "= Annual Interest Paid", "Alternative source: Accepted Form 1098 Box 1"],
        [_input("monthly_interest", "Monthly Interest", "Accepted monthly interest values."), _input("form_1098_box_1", "Form 1098 Box 1", "Reported mortgage interest for the tax year.")],
        source_priority=["Accepted Form 1098 Box 1", "Accepted year-end statement", "Backend amortization schedule"],
        source_type="mixed",
        display_format="currency / year",
    ),
    _formula(
        "loan.annual_principal_paid", "loans", "yearly-reconciliation", "Annual Principal Paid",
        "Principal reduction for a loan during a year.",
        ["Sum of Monthly Principal Payments + Extra Principal Payments = Annual Principal Paid", "Opening Balance − Ending Balance + Adjustments = Annual Principal Paid"],
        [_input("monthly_principal", "Monthly Principal", "Accepted monthly principal."), _input("extra_principal", "Extra Principal", "Accepted principal beyond schedule."), _input("opening_balance", "Opening Balance", "Year opening balance."), _input("ending_balance", "Ending Balance", "Year ending balance.")],
        source_type="mixed",
        display_format="currency / year",
    ),
    _formula(
        "loan.projected_principal", "loans", "yearly-reconciliation", "Projected Principal",
        "Scheduled principal from the backend amortization schedule.",
        ["Sum of Scheduled Principal from Backend Amortization Schedule", "= Projected Principal"],
        [_input("scheduled_principal", "Scheduled Principal", "Backend amortization principal rows.")],
        source_type="projected",
        assumptions=["For current-year comparisons, backend uses projected YTD when comparing to actual YTD."],
        display_format="currency",
    ),
    _formula(
        "loan.principal_top_up", "loans", "extra-principal", "Principal Top-Up",
        "Accepted principal paid beyond projected scheduled principal.",
        ["Accepted Principal Paid", "− Projected Scheduled Principal", "= Principal Top-Up"],
        [_input("accepted_principal_paid", "Accepted Principal Paid", "Reported or accepted principal reduction."), _input("projected_principal", "Projected Scheduled Principal", "Scheduled amortization principal.")],
        source_type="derived",
        assumptions=["Positive means extra principal was paid; negative means the record is incomplete, inconsistent, modified, deferred, or incorrectly reconciled."],
        display_format="currency",
    ),
    _formula(
        "loan.balance_chain_difference", "loans", "yearly-reconciliation", "Balance Chain Validation",
        "Checks whether one year's ending balance ties to the next year's opening balance.",
        ["Previous Year Ending Balance", "− Current Year Opening Balance", "= Balance Chain Difference"],
        [_input("previous_ending_balance", "Previous Year Ending Balance", "Accepted ending balance for prior year."), _input("current_opening_balance", "Current Year Opening Balance", "Accepted opening balance for current year.")],
        source_type="calculated",
        assumptions=["Expected result is $0. Non-zero differences create reconciliation issues."],
        display_format="currency",
    ),
    _formula(
        "loan.interest_variance", "loans", "yearly-reconciliation", "Interest Variance",
        "Difference between reported interest and projected interest.",
        ["Reported Interest − Projected Interest = Interest Difference", "Absolute Interest Difference ÷ Projected Interest × 100 = Interest Variance Percentage"],
        [_input("reported_interest", "Reported Interest", "Accepted reported interest."), _input("projected_interest", "Projected Interest", "Backend scheduled interest.")],
        source_type="derived",
        display_format="currency / percentage",
    ),
    _formula(
        "loan.remaining_term", "loans", "loan-summary", "Remaining Term",
        "Time or scheduled payment count remaining on the loan.",
        ["Loan Maturity Date − Current Date = Remaining Loan Term"],
        [_input("maturity_date", "Maturity Date", "Loan maturity date.", "date"), _input("current_date", "Current Date", "Backend as-of date.", "date")],
        source_type="calculated",
        display_format="duration",
    ),
    _formula(
        "loan.payoff_date_with_extra_payment", "loans", "payoff-scenarios", "Payoff Date with Extra Payment",
        "Projected payoff date after scenario extra payments are applied.",
        ["Backend amortization engine simulates payment by payment until balance reaches zero"],
        [_input("scheduled_payment", "Scheduled Payment", "Base P&I payment."), _input("extra_payment", "Extra Payment", "Scenario extra principal."), _input("loan_balance", "Loan Balance", "Starting balance.")],
        source_type="projected",
        assumptions=["Frontend never calculates payoff dates."],
        display_format="date",
    ),
    _formula(
        "loan.interest_saved", "loans", "payoff-scenarios", "Interest Saved",
        "Projected remaining interest avoided by a payoff scenario.",
        ["Projected Remaining Interest Without Extra Payments", "− Projected Remaining Interest With Extra Payments", "= Interest Saved"],
        [_input("baseline_interest", "Baseline Remaining Interest", "Projected interest without extra payments."), _input("scenario_interest", "Scenario Remaining Interest", "Projected interest with scenario payments.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "loan.time_saved", "loans", "payoff-scenarios", "Time Saved",
        "Difference between baseline payoff date and accelerated payoff date.",
        ["Original Projected Payoff Date", "− Accelerated Payoff Date", "= Time Saved"],
        [_input("baseline_payoff_date", "Original Projected Payoff Date", "Payoff without extra payment.", "date"), _input("accelerated_payoff_date", "Accelerated Payoff Date", "Scenario payoff date.", "date")],
        source_type="projected",
        display_format="duration",
    ),
    _formula(
        "rental.gross_rental_income", "rental", "rental-income", "Gross Rental Income",
        "Accepted rent income for the selected period.",
        ["Sum of Accepted Rent Payments = Gross Rental Income", "Projected Rent = Monthly Scheduled Rent × Occupied Months"],
        [_input("rent_payments", "Rent Payments", "Accepted rent amounts."), _input("monthly_scheduled_rent", "Monthly Scheduled Rent", "Backend-resolved monthly rent."), _input("occupied_months", "Occupied Months", "Backend occupancy duration.", "duration")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "rental.other_income", "rental", "rental-income", "Other Rental Income",
        "Accepted non-rent property income.",
        ["Sum of Accepted Non-Rent Property Income = Other Rental Income"],
        [_input("other_income", "Other Income", "Parking, laundry, storage, pet fees, reimbursements, or other accepted property income.")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "rental.total_property_income", "rental", "rental-income", "Total Property Income",
        "Total accepted property income from rent and other sources.",
        ["Gross Rental Income + Other Rental Income = Total Property Income"],
        [_input("gross_rental_income", "Gross Rental Income", "Accepted rent income."), _input("other_income", "Other Rental Income", "Accepted non-rent property income.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "rental.occupied_days", "rental", "occupancy", "Occupied Days",
        "Days marked occupied during the selected period.",
        ["Count of Days Marked Occupied During the Selected Period = Occupied Days"],
        [_input("occupancy_periods", "Occupancy Periods", "Backend occupancy log periods.", "duration")],
        source_type="derived",
        display_format="integer",
    ),
    _formula(
        "rental.available_days", "rental", "occupancy", "Available Days",
        "Days the property was available for rent during the selected period.",
        ["Rental Availability End Date − Rental Availability Start Date + 1 = Available Days"],
        [_input("rental_available_from", "Rental Available From", "Start of rental availability.", "date"), _input("rental_available_until", "Rental Available Until", "End of rental availability or backend as-of date.", "date")],
        source_type="derived",
        exclusions=["Periods where the property was not available for rent are excluded."],
        display_format="integer",
    ),
    _formula(
        "rental.vacant_days", "rental", "vacancy", "Vacant Days",
        "Available rental days without an occupied period.",
        ["Available Days − Occupied Days = Vacant Days"],
        [_input("available_days", "Available Days", "Backend rental availability days.", "integer"), _input("occupied_days", "Occupied Days", "Backend occupied days.", "integer")],
        source_type="derived",
        display_format="integer",
    ),
    _formula(
        "rental.occupancy_rate", "rental", "occupancy", "Occupancy Rate",
        "Occupied time as a percentage of available rental time.",
        ["Occupied Days ÷ Available Days × 100 = Occupancy Rate"],
        [_input("occupied_days", "Occupied Days", "Backend occupied days.", "integer"), _input("available_days", "Available Days", "Backend available days.", "integer")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "rental.vacancy_rate", "rental", "vacancy", "Vacancy Rate",
        "Vacant time as a percentage of available rental time.",
        ["Vacant Days ÷ Available Days × 100 = Vacancy Rate", "or 100% − Occupancy Rate = Vacancy Rate"],
        [_input("vacant_days", "Vacant Days", "Backend vacant days.", "integer"), _input("available_days", "Available Days", "Backend available days.", "integer")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "rental.rent_growth", "rental", "rent-growth", "Rent Growth",
        "Change from previous monthly rent to current monthly rent.",
        ["Current Monthly Rent − Previous Monthly Rent = Rent Increase", "Rent Increase ÷ Previous Monthly Rent × 100 = Rent Growth Percentage"],
        [_input("current_monthly_rent", "Current Monthly Rent", "Backend-resolved current rent."), _input("previous_monthly_rent", "Previous Monthly Rent", "Prior accepted rent.")],
        source_type="calculated",
        display_format="currency / percentage",
    ),
    _formula(
        "rental.rent_per_square_foot", "rental", "rental-performance", "Rent per Square Foot",
        "Monthly rent divided by livable square feet.",
        ["Monthly Rent ÷ Livable Square Feet = Monthly Rent per Square Foot"],
        [_input("monthly_rent", "Monthly Rent", "Backend-resolved monthly rent."), _input("livable_square_feet", "Livable Square Feet", "Accepted square footage.", "decimal")],
        source_type="calculated",
        assumptions=["Only shown when square footage is available."],
        display_format="currency / square foot",
    ),
    _formula(
        "expense.total_operating_expenses", "expenses", "operating-expenses", "Total Operating Expenses",
        "Recurring property operating costs used by NOI.",
        ["Property Taxes + Insurance + HOA + Repairs + Maintenance + Property Management + Utilities Paid by Owner + Licensing + Advertising + Legal and Professional Fees + Other Operating Expenses = Total Operating Expenses"],
        [_input("property_tax", "Property Taxes", "Resolved property tax expense."), _input("insurance", "Insurance", "Resolved insurance expense."), _input("hoa", "HOA", "HOA payments."), _input("repairs", "Repairs and Maintenance", "Accepted repair and maintenance expenses."), _input("management", "Property Management", "Management fees."), _input("utilities", "Utilities", "Owner-paid utilities."), _input("other", "Other Operating Expenses", "Other accepted operating expenses.")],
        source_type="mixed",
        exclusions=["Mortgage principal", "Mortgage interest when calculating NOI", "Depreciation", "Income taxes", "Acquisition costs", "Capital improvements"],
        display_format="currency / year",
    ),
    _formula(
        "expense.monthly_operating_expense", "expenses", "operating-expenses", "Monthly Operating Expense",
        "Average monthly operating expense or actual month expense depending on backend mode.",
        ["Annual Operating Expenses ÷ 12 = Average Monthly Operating Expense", "Actual monthly mode: Sum of Expenses Posted in the Month = Actual Monthly Operating Expense"],
        [_input("annual_operating_expenses", "Annual Operating Expenses", "Backend-resolved annual opex."), _input("monthly_expense_records", "Monthly Expense Records", "Accepted monthly expense rows.")],
        source_type="calculated",
        assumptions=["The UI must label average monthly values when they are annual amounts divided by 12."],
        display_format="currency / month",
    ),
    _formula(
        "expense.property_tax", "expenses", "operating-expenses", "Property Tax Expense",
        "Accepted property tax expense for the selected period.",
        ["Sum of Accepted Property Tax Payments for the Period = Property Tax Expense"],
        [_input("property_tax_payments", "Property Tax Payments", "Accepted tax bills, payments, or allocated amounts.")],
        source_priority=["Property tax bill or payment record", "Escrow disbursement", "Mortgage statement", "User-entered amount", "Estimate"],
        source_type="mixed",
        assumptions=["Escrow contributions and escrow-funded tax disbursements are not double-counted."],
        display_format="currency",
    ),
    _formula(
        "expense.insurance", "expenses", "operating-expenses", "Insurance Expense",
        "Accepted insurance premium allocated to the selected period.",
        ["Sum of Accepted Insurance Premiums Allocated to the Period = Insurance Expense", "Annual Insurance Premium ÷ 12 = Monthly Insurance Expense"],
        [_input("insurance_premiums", "Insurance Premiums", "Accepted insurance documents, statements, or manual values.")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "expense.hoa", "expenses", "operating-expenses", "HOA Expense",
        "HOA payments during the selected period.",
        ["Sum of HOA Payments During the Period = HOA Expense"],
        [_input("hoa_payments", "HOA Payments", "Accepted HOA expenses.")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "expense.repairs_maintenance", "expenses", "operating-expenses", "Repairs and Maintenance",
        "Accepted expenses classified as repairs and maintenance.",
        ["Sum of Expenses Classified as Repairs and Maintenance = Repairs and Maintenance Expense"],
        [_input("repairs_maintenance", "Repairs and Maintenance", "Accepted repair and maintenance expenses.")],
        source_type="mixed",
        exclusions=["Capital improvements are not automatically classified as repairs."],
        display_format="currency",
    ),
    _formula(
        "expense.property_management", "expenses", "operating-expenses", "Property Management Expense",
        "Accepted or estimated property management fees.",
        ["Sum of Management Fees During the Period = Property Management Expense", "Estimate: Gross Collected Rent × Management Fee Rate = Estimated Management Fee"],
        [_input("management_fees", "Management Fees", "Accepted property management expenses."), _input("gross_collected_rent", "Gross Collected Rent", "Accepted collected rent."), _input("management_fee_rate", "Management Fee Rate", "Configured management percentage.", "percentage")],
        source_type="mixed",
        assumptions=["Percentage estimates are labeled Estimated when no actual value exists."],
        display_format="currency",
    ),
    _formula(
        "expense.debt_service", "expenses", "financing-expenses", "Debt Service",
        "Cash paid toward mortgage principal and interest.",
        ["Mortgage Principal + Mortgage Interest = Principal and Interest Debt Service", "Principal + Interest + Escrow Contribution = Total Mortgage Payment"],
        [_input("principal", "Mortgage Principal", "Principal paid."), _input("interest", "Mortgage Interest", "Interest paid."), _input("escrow", "Escrow Contribution", "Escrow payment mechanism.")],
        source_type="mixed",
        assumptions=["Escrow contributions are not final expenses when actual tax and insurance disbursements are separately tracked."],
        display_format="currency",
    ),
    _formula(
        "expense.total_cash_outflow", "expenses", "financing-expenses", "Total Cash Outflow",
        "Total cash leaving the property for operations, debt, capital expenditures, and other outflows.",
        ["Operating Expenses + Debt Service + Capital Expenditures + Other Cash Outflows = Total Cash Outflow"],
        [_input("operating_expenses", "Operating Expenses", "Backend-resolved opex."), _input("debt_service", "Debt Service", "Principal and interest debt service."), _input("capital_expenditures", "Capital Expenditures", "Accepted capital outflows."), _input("other_cash_outflows", "Other Cash Outflows", "Other backend-classified cash outflows.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "expense.capital_expenditures", "expenses", "capital-expenses", "Capital Expenditures",
        "Expenses classified as capital improvements.",
        ["Sum of Expenses Classified as Capital Improvements = Capital Expenditures"],
        [_input("capital_improvements", "Capital Improvements", "Accepted capitalized improvements.")],
        source_type="mixed",
        exclusions=["Capital expenditures do not automatically reduce NOI unless a backend cash-flow-after-capex metric explicitly includes them."],
        display_format="currency",
    ),
    _formula(
        "expense.expense_ratio", "expenses", "expense-trends", "Expense Ratio",
        "Operating expenses as a percentage of gross property income.",
        ["Operating Expenses ÷ Gross Property Income × 100 = Operating Expense Ratio"],
        [_input("operating_expenses", "Operating Expenses", "Backend-resolved opex."), _input("gross_property_income", "Gross Property Income", "Accepted property income.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "expense.cost_to_own", "expenses", "recurring-expenses", "Cost to Own",
        "Cash ownership cost before non-cash depreciation.",
        ["Operating Expenses + Debt Service + Recurring Owner-Paid Costs = Cost to Own", "Annual Cost to Own ÷ 12 = Monthly Cost to Own"],
        [_input("operating_expenses", "Operating Expenses", "Backend-resolved opex."), _input("debt_service", "Debt Service", "Principal and interest debt service."), _input("recurring_owner_costs", "Recurring Owner-Paid Costs", "Other backend-classified recurring costs.")],
        source_type="calculated",
        exclusions=["Depreciation is excluded because it is non-cash."],
        display_format="currency",
    ),
    _formula(
        "expense.year_over_year_change", "expenses", "expense-trends", "Year-over-Year Expense Change",
        "Change in an expense value compared with the previous year.",
        ["Current Year Expense − Previous Year Expense = Expense Change", "Expense Change ÷ Previous Year Expense × 100 = Expense Change Percentage"],
        [_input("current_year_expense", "Current Year Expense", "Selected year's expense."), _input("previous_year_expense", "Previous Year Expense", "Prior year's expense.")],
        source_type="calculated",
        assumptions=["Backend handles zero prior-year values without division-by-zero errors."],
        display_format="currency / percentage",
    ),
    _formula(
        "tax.taxable_rental_income", "taxes", "rental-tax-summary", "Taxable Rental Income",
        "Estimated rental income after deductible expenses, mortgage interest, depreciation, and other allowed deductions.",
        ["Rental Income − Deductible Operating Expenses − Deductible Mortgage Interest − Allowed Depreciation − Other Allowed Deductions = Estimated Taxable Rental Income"],
        [_input("rental_income", "Rental Income", "Tax-year rental income."), _input("deductible_operating_expenses", "Deductible Operating Expenses", "Backend tax-deductible expense categories."), _input("mortgage_interest", "Deductible Mortgage Interest", "Accepted mortgage interest."), _input("allowed_depreciation", "Allowed Depreciation", "Backend depreciation deduction.")],
        source_type="calculated",
        assumptions=["PropertyLens provides calculation support and record organization. It does not provide tax, legal, or accounting advice."],
        display_format="currency",
    ),
    _formula(
        "tax.cash_noi", "taxes", "rental-tax-summary", "Cash NOI",
        "Rental operating income before financing and non-cash depreciation.",
        ["Rental Income + Other Property Income − Cash Operating Expenses = Cash NOI"],
        [_input("rental_income", "Rental Income", "Accepted rent."), _input("other_property_income", "Other Property Income", "Accepted non-rent income."), _input("cash_operating_expenses", "Cash Operating Expenses", "Cash opex selected by backend.")],
        source_type="calculated",
        exclusions=["Depreciation", "Mortgage principal"],
        display_format="currency",
    ),
    _formula(
        "tax.profit_or_loss", "taxes", "taxable-rental-income", "Tax Profit or Loss",
        "Estimated rental tax profit or loss.",
        ["Rental Income − Tax-Deductible Expenses − Allowed Depreciation = Estimated Tax Profit or Loss"],
        [_input("rental_income", "Rental Income", "Tax-year rental income."), _input("tax_deductible_expenses", "Tax-Deductible Expenses", "Backend deductible categories."), _input("allowed_depreciation", "Allowed Depreciation", "Backend depreciation deduction.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "tax.accumulated_depreciation", "taxes", "taxable-rental-income", "Accumulated Depreciation",
        "Depreciation claimed or allowed through the selected date.",
        ["Sum of Depreciation Claimed or Allowed Through the Selected Date = Accumulated Depreciation"],
        [_input("depreciation_entries", "Depreciation Entries", "Backend depreciation schedule or accepted filed data.")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "tax.personal_use_allocation", "taxes", "suspended-or-disallowed-items", "Personal Use Allocation",
        "Rental-use percentage for mixed-use allocation where supported.",
        ["Rental Use Days ÷ Total Use Days × 100 = Rental-Use Percentage"],
        [_input("rental_use_days", "Rental Use Days", "Backend rental-use days.", "integer"), _input("total_use_days", "Total Use Days", "Backend total use days.", "integer")],
        source_type="calculated",
        assumptions=["Backend applies the application-defined allocation rules; the UI does not infer legal deductibility."],
        display_format="percentage",
    ),
    _formula(
        "depreciation.total_cost_basis", "depreciation", "depreciable-basis", "Total Cost Basis",
        "Total acquisition basis before land and non-depreciable exclusions.",
        ["Purchase Price + Capitalized Acquisition Costs + Capital Improvements Before Service − Seller Credits Allocated Against Basis = Total Cost Basis"],
        [_input("purchase_price", "Purchase Price", "Accepted acquisition price."), _input("capitalized_acquisition_costs", "Capitalized Acquisition Costs", "Backend-configured capitalized closing costs."), _input("capital_improvements_before_service", "Capital Improvements Before Service", "Capitalized improvements before service."), _input("seller_credits", "Seller Credits", "Credits allocated against basis.")],
        source_type="mixed",
        assumptions=["Exact included closing-cost categories come from backend configuration."],
        display_format="currency",
    ),
    _formula(
        "depreciation.land_value", "depreciation", "land-allocation", "Land Value",
        "Accepted value allocated to land, which is not depreciated.",
        ["Accepted land valuation = Land Value"],
        [_input("land_value", "Land Value", "Accepted appraisal, assessment, manual allocation, or other supported source.")],
        source_type="mixed",
        exclusions=["Land is not depreciated."],
        display_format="currency",
    ),
    _formula(
        "depreciation.building_allocation_percentage", "depreciation", "land-allocation", "Building Allocation Percentage",
        "Building share of total land and building value.",
        ["Building Value ÷ Total Land and Building Value × 100 = Building Allocation Percentage"],
        [_input("building_value", "Building Value", "Accepted building allocation."), _input("total_land_building_value", "Total Land and Building Value", "Accepted combined allocation value.")],
        source_type="calculated",
        display_format="percentage",
    ),
    _formula(
        "depreciation.building_basis", "depreciation", "building-basis", "Depreciable Building Basis",
        "Depreciable basis allocated to the building after excluding land and non-depreciable amounts.",
        ["Total Cost Basis − Land Value − Non-Depreciable Amounts = Depreciable Building Basis", "Alternative: Total Cost Basis × Building Allocation Percentage = Depreciable Building Basis"],
        [_input("total_cost_basis", "Total Cost Basis", "Backend accepted basis."), _input("land_value", "Land Value", "Accepted land value."), _input("non_depreciable_amounts", "Non-Depreciable Amounts", "Backend exclusions.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "depreciation.improvement_basis", "depreciation", "improvements", "Improvement Basis",
        "Capitalized basis for one improvement asset.",
        ["Capitalized Improvement Cost + Capitalized Improvement-Related Costs = Improvement Basis"],
        [_input("improvement_cost", "Improvement Cost", "Accepted capitalized improvement cost."), _input("related_costs", "Related Costs", "Accepted capitalized related costs.")],
        source_type="mixed",
        assumptions=["Each improvement maintains its own placed-in-service date, recovery period, method, and accumulated depreciation."],
        display_format="currency",
    ),
    _formula(
        "depreciation.total_depreciable_basis", "depreciation", "depreciable-basis", "Total Depreciable Basis",
        "Total active depreciable basis for building and improvements.",
        ["Building Depreciable Basis + Active Improvement Bases = Total Depreciable Basis"],
        [_input("building_basis", "Building Basis", "Depreciable building basis."), _input("improvement_bases", "Improvement Bases", "Active improvement bases.")],
        source_type="calculated",
        assumptions=["Assets with different recovery periods are not combined unless the backend explicitly supports that method."],
        display_format="currency",
    ),
    _formula(
        "depreciation.annual_straight_line", "depreciation", "annual-depreciation", "Annual Straight-Line Depreciation",
        "Full-year straight-line depreciation for a depreciable asset.",
        ["Depreciable Basis ÷ Recovery Period = Full-Year Depreciation"],
        [_input("depreciable_basis", "Depreciable Basis", "Asset basis after exclusions."), _input("recovery_period", "Recovery Period", "Backend tax-engine recovery period.", "duration")],
        source_type="calculated",
        assumptions=["Residential rental recovery period is configured by the backend tax engine and not hard-coded in the UI."],
        display_format="currency / year",
    ),
    _formula(
        "depreciation.partial_year", "depreciation", "partial-year-depreciation", "Partial-Year Depreciation",
        "First-year or partial-use depreciation after backend convention is applied.",
        ["Full-Year Depreciation × Applicable First-Year Convention Percentage = First-Year Depreciation"],
        [_input("full_year_depreciation", "Full-Year Depreciation", "Annual straight-line amount."), _input("convention_percentage", "Convention Percentage", "Backend-selected convention percentage.", "percentage")],
        source_type="calculated",
        assumptions=["The backend determines the applicable convention and percentage."],
        display_format="currency",
    ),
    _formula(
        "depreciation.accumulated", "depreciation", "accumulated-depreciation", "Accumulated Depreciation",
        "Total allowed or recorded depreciation through the selected date.",
        ["Sum of Annual Allowed or Recorded Depreciation = Accumulated Depreciation"],
        [_input("annual_depreciation_rows", "Annual Depreciation Rows", "Backend depreciation schedule rows.")],
        source_type="mixed",
        display_format="currency",
    ),
    _formula(
        "depreciation.remaining_basis", "depreciation", "remaining-basis", "Remaining Depreciable Basis",
        "Undepreciated basis remaining for active depreciable assets.",
        ["Original Depreciable Basis − Accumulated Depreciation = Remaining Depreciable Basis"],
        [_input("original_depreciable_basis", "Original Depreciable Basis", "Initial asset basis."), _input("accumulated_depreciation", "Accumulated Depreciation", "Allowed or recorded depreciation.")],
        source_type="calculated",
        assumptions=["Backend does not allow the result to go below zero unless an explicit adjustment exists."],
        display_format="currency",
    ),
    _formula(
        "depreciation.book_value", "depreciation", "remaining-basis", "Book Value",
        "Adjusted book value after accumulated depreciation.",
        ["Total Cost Basis − Accumulated Depreciation = Adjusted Book Value"],
        [_input("total_cost_basis", "Total Cost Basis", "Accepted cost basis."), _input("accumulated_depreciation", "Accumulated Depreciation", "Allowed or recorded depreciation.")],
        source_type="calculated",
        assumptions=["Book value is distinct from market value."],
        display_format="currency",
    ),
    _formula(
        "depreciation.average_annual_display", "depreciation", "annual-depreciation", "Average Annual Depreciation Display",
        "Average annual depreciation when an average is explicitly displayed.",
        ["Accumulated Depreciation ÷ Number of Depreciation Years = Average Annual Depreciation"],
        [_input("accumulated_depreciation", "Accumulated Depreciation", "Allowed or recorded depreciation."), _input("depreciation_years", "Depreciation Years", "Count of depreciation years.", "duration")],
        source_type="calculated",
        assumptions=["This must not be labeled as the current-year tax deduction."],
        display_format="currency / year",
    ),
    _formula(
        "scenario.extra_monthly_payment", "scenarios", "extra-monthly-payment", "Extra Monthly Payment",
        "Scenario extra principal applied to scheduled monthly payment.",
        ["Scheduled Payment + Extra Monthly Principal = Scenario Monthly Payment"],
        [_input("scheduled_payment", "Scheduled Payment", "Backend scheduled P&I payment."), _input("extra_monthly_principal", "Extra Monthly Principal", "Scenario assumption.")],
        source_type="projected",
        display_format="currency / month",
    ),
    _formula(
        "scenario.annual_lump_sum", "scenarios", "annual-lump-sum-payment", "Annual Lump-Sum Principal",
        "Annual lump-sum principal applied on the configured scenario date.",
        ["Balance Before Lump Sum − Lump-Sum Principal = Balance After Lump Sum"],
        [_input("balance_before_lump_sum", "Balance Before Lump Sum", "Projected balance before event."), _input("lump_sum_principal", "Lump-Sum Principal", "Scenario lump-sum assumption.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.combined_extra_payment", "scenarios", "extra-monthly-payment", "Combined Extra Payment",
        "Total scenario principal from scheduled and extra payments.",
        ["Scheduled Principal + Recurring Extra Principal + Lump-Sum Principal = Total Scenario Principal Paid"],
        [_input("scheduled_principal", "Scheduled Principal", "Projected scheduled principal."), _input("recurring_extra_principal", "Recurring Extra Principal", "Scenario recurring extra principal."), _input("lump_sum_principal", "Lump-Sum Principal", "Scenario lump-sum principal.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.projected_total_interest", "scenarios", "extra-monthly-payment", "Projected Total Interest",
        "Future interest projected by the backend scenario schedule.",
        ["Sum of All Future Projected Interest Payments = Projected Total Remaining Interest"],
        [_input("future_interest_payments", "Future Interest Payments", "Backend scenario interest rows.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.projected_interest_saved", "scenarios", "extra-monthly-payment", "Projected Interest Saved",
        "Difference between baseline remaining interest and scenario remaining interest.",
        ["Baseline Remaining Interest − Scenario Remaining Interest = Projected Interest Saved"],
        [_input("baseline_remaining_interest", "Baseline Remaining Interest", "Projected interest without scenario change."), _input("scenario_remaining_interest", "Scenario Remaining Interest", "Projected interest under scenario.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.projected_cash_flow", "scenarios", "rent-increase", "Projected Cash Flow",
        "Projected net cash flow under scenario assumptions.",
        ["Projected Rental Income + Projected Other Income − Projected Operating Expenses − Projected Debt Service = Projected Net Cash Flow"],
        [_input("projected_rental_income", "Projected Rental Income", "Scenario rental income."), _input("projected_other_income", "Projected Other Income", "Scenario other income."), _input("projected_operating_expenses", "Projected Operating Expenses", "Scenario opex."), _input("projected_debt_service", "Projected Debt Service", "Scenario debt service.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.sale_proceeds", "scenarios", "sale", "Sale Proceeds",
        "Estimated net proceeds from a scenario sale.",
        ["Projected Sale Price − Selling Costs − Remaining Loan Payoff − Other Sale Liabilities = Estimated Net Sale Proceeds"],
        [_input("projected_sale_price", "Projected Sale Price", "Scenario sale price."), _input("selling_costs", "Selling Costs", "Scenario selling costs."), _input("remaining_loan_payoff", "Remaining Loan Payoff", "Projected payoff."), _input("other_sale_liabilities", "Other Sale Liabilities", "Other backend-classified liabilities.")],
        source_type="projected",
        display_format="currency",
    ),
    _formula(
        "scenario.projected_sale_price", "scenarios", "appreciation", "Projected Sale Price",
        "Scenario sale price based on appreciation assumption.",
        ["Current Market Value × (1 + Annual Appreciation Rate)^Holding Years = Projected Sale Price"],
        [_input("current_market_value", "Current Market Value", "Latest accepted value."), _input("annual_appreciation_rate", "Annual Appreciation Rate", "Scenario assumption.", "percentage"), _input("holding_years", "Holding Years", "Scenario hold period.", "duration")],
        source_type="projected",
        assumptions=["This is a scenario assumption, not a forecast guarantee."],
        display_format="currency",
    ),
    _formula(
        "scenario.selling_cost", "scenarios", "sale", "Selling Cost",
        "Estimated selling cost under a percentage or fixed-cost scenario.",
        ["Projected Sale Price × Selling Cost Percentage = Estimated Selling Cost"],
        [_input("projected_sale_price", "Projected Sale Price", "Scenario sale price."), _input("selling_cost_percentage", "Selling Cost Percentage", "Scenario selling cost rate.", "percentage")],
        source_type="projected",
        assumptions=["Fixed selling costs are used where supported by the backend scenario."],
        display_format="currency",
    ),
    _formula(
        "scenario.total_return", "scenarios", "hold-period", "Scenario Total Return",
        "Scenario return after cumulative cash flow and sale proceeds.",
        ["Cumulative Net Cash Flow + Net Sale Proceeds − Initial Cash Invested = Scenario Total Return"],
        [_input("cumulative_net_cash_flow", "Cumulative Net Cash Flow", "Scenario cash-flow total."), _input("net_sale_proceeds", "Net Sale Proceeds", "Scenario sale proceeds."), _input("initial_cash_invested", "Initial Cash Invested", "Backend-selected initial cash.")],
        source_type="projected",
        assumptions=["Where appreciation and loan payoff are already reflected in net sale proceeds, they are not added again."],
        display_format="currency",
    ),
    _formula(
        "scenario.roi", "scenarios", "hold-period", "Scenario ROI",
        "Scenario total return divided by initial cash invested.",
        ["Scenario Total Return ÷ Initial Cash Invested × 100 = Scenario ROI"],
        [_input("scenario_total_return", "Scenario Total Return", "Projected total return."), _input("initial_cash_invested", "Initial Cash Invested", "Backend-selected initial cash.")],
        source_type="projected",
        display_format="percentage",
    ),
    _formula(
        "scenario.annualized_return", "scenarios", "hold-period", "Annualized Scenario Return",
        "Simple or compounded annualized return under a scenario.",
        ["Simple: Scenario ROI ÷ Holding Years = Simple Annualized Return", "Compounded: (Final Value ÷ Initial Investment)^(1 ÷ Holding Years) − 1 = Annualized Compounded Return"],
        [_input("scenario_roi", "Scenario ROI", "Scenario return percentage.", "percentage"), _input("holding_years", "Holding Years", "Scenario hold period.", "duration"), _input("final_value", "Final Value", "Backend scenario final value."), _input("initial_investment", "Initial Investment", "Backend scenario initial investment.")],
        source_type="projected",
        assumptions=["Simple and compounded annualized returns use distinct labels."],
        display_format="percentage",
    ),
    _formula(
        "portfolio.value", "portfolio", "portfolio-summary", "Portfolio Value",
        "Total current market value for included properties.",
        ["Sum of Current Market Values for Included Properties = Portfolio Value"],
        [_input("property_market_values", "Property Market Values", "Included property values.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "portfolio.equity", "portfolio", "portfolio-summary", "Portfolio Equity",
        "Portfolio value after active loan balances.",
        ["Portfolio Value − Sum of Active Loan Balances = Portfolio Equity"],
        [_input("portfolio_value", "Portfolio Value", "Sum of included property values."), _input("active_loan_balances", "Active Loan Balances", "Sum of active loan balances.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "portfolio.net_cash_flow", "portfolio", "portfolio-summary", "Portfolio Net Cash Flow",
        "Sum of property net cash flows.",
        ["Sum of Property Net Cash Flows = Portfolio Net Cash Flow"],
        [_input("property_cash_flows", "Property Cash Flows", "Backend property cash-flow metrics.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "portfolio.noi", "portfolio", "portfolio-summary", "Portfolio NOI",
        "Sum of property NOI metrics.",
        ["Sum of Property NOI = Portfolio NOI"],
        [_input("property_noi", "Property NOI", "Backend property NOI metrics.")],
        source_type="calculated",
        display_format="currency",
    ),
    _formula(
        "portfolio.ltv", "portfolio", "portfolio-ratios", "Portfolio LTV",
        "Portfolio loan-to-value ratio using portfolio totals.",
        ["Total Active Loan Balance ÷ Total Portfolio Market Value × 100 = Portfolio LTV"],
        [_input("active_loan_balance", "Active Loan Balance", "Portfolio active debt."), _input("portfolio_market_value", "Portfolio Market Value", "Total included property value.")],
        source_type="calculated",
        assumptions=["Do not average individual property LTV percentages."],
        display_format="percentage",
    ),
    _formula(
        "portfolio.cap_rate", "portfolio", "portfolio-ratios", "Portfolio Cap Rate",
        "Portfolio cap rate using total NOI and total market value.",
        ["Total Portfolio NOI ÷ Total Portfolio Market Value × 100 = Portfolio Cap Rate"],
        [_input("portfolio_noi", "Portfolio NOI", "Sum of property NOI."), _input("portfolio_market_value", "Portfolio Market Value", "Total included property value.")],
        source_type="calculated",
        assumptions=["Do not average property cap rates."],
        display_format="percentage",
    ),
    _formula(
        "portfolio.dscr", "portfolio", "portfolio-ratios", "Debt Service Coverage Ratio",
        "NOI divided by annual debt service.",
        ["NOI ÷ Annual Debt Service = DSCR"],
        [_input("noi", "NOI", "Backend NOI metric."), _input("annual_debt_service", "Annual Debt Service", "Principal and interest debt service.")],
        source_type="calculated",
        assumptions=["If debt service is zero, backend returns Not Applicable rather than dividing by zero."],
        display_format="ratio",
    ),
    _formula(
        "portfolio.occupancy_rate", "portfolio", "portfolio-ratios", "Weighted Portfolio Occupancy",
        "Portfolio occupancy weighted by available rental days.",
        ["Total Occupied Available Days Across Properties ÷ Total Available Days Across Properties × 100 = Portfolio Occupancy Rate"],
        [_input("occupied_available_days", "Occupied Available Days", "Occupied days across included properties.", "integer"), _input("available_days", "Available Days", "Available rental days across included properties.", "integer")],
        source_type="calculated",
        assumptions=["Do not use a simple average of property occupancy rates."],
        display_format="percentage",
    ),
    _formula(
        "source.reported", "documents", "source-labels", "Reported",
        "A value directly obtained from an accepted document or imported record.",
        ["Accepted document or imported record = Reported value"],
        [_input("source_document", "Source Document", "Accepted document or imported record.", "integer")],
        source_type="reported",
        calculation_frequency="When a source document is accepted, replaced, or removed",
    ),
    _formula(
        "source.calculated", "documents", "source-labels", "Calculated",
        "A value produced by a deterministic backend calculation.",
        ["Backend engine inputs + deterministic formula = Calculated value"],
        [_input("backend_inputs", "Backend Inputs", "Accepted source values used by the engine.")],
        source_type="calculated",
    ),
    _formula(
        "source.derived", "documents", "source-labels", "Derived",
        "A value inferred from two or more accepted values.",
        ["Accepted Value A + Accepted Value B + Backend rule = Derived value"],
        [_input("accepted_values", "Accepted Values", "Values accepted by the backend source engine.")],
        source_type="derived",
    ),
    _formula(
        "source.projected", "documents", "source-labels", "Projected",
        "A forward-looking value produced from a schedule or scenario.",
        ["Schedule or scenario assumptions = Projected value"],
        [_input("scenario_inputs", "Scenario Inputs", "Backend scenario or schedule inputs.")],
        source_type="projected",
    ),
    _formula(
        "source.estimated", "documents", "source-labels", "Estimated",
        "A value based on incomplete data or a documented assumption.",
        ["Partial source + Backend estimate rule = Estimated value"],
        [_input("partial_source", "Partial Source", "Incomplete source data.")],
        source_type="estimated",
    ),
    _formula(
        "source.manual", "documents", "source-labels", "Manual",
        "A value entered or overridden by the user.",
        ["User-entered accepted value = Manual value"],
        [_input("manual_entry", "Manual Entry", "User-entered value.")],
        source_type="manual",
    ),
    _formula(
        "reconciliation.issue", "reconciliation", "issue-types", "Reconciliation Issue",
        "A difference between accepted or expected values that exceeds backend tolerance.",
        ["Accepted Source Value − Expected or Related Value = Reconciliation Difference"],
        [_input("accepted_value", "Accepted Value", "Accepted source value."), _input("expected_value", "Expected Value", "Related backend expected value."), _input("tolerance", "Tolerance", "Backend configured tolerance.")],
        source_type="calculated",
        assumptions=["An issue does not automatically mean the source document is wrong."],
        related=["loan.balance_chain_difference", "loan.interest_variance"],
    ),
    _formula(
        "convention.rounding", "conventions", "rounding", "Rounding",
        "System-wide rounding convention.",
        ["Backend stores full precision", "Display layer rounds only for presentation unless a financial rule requires transactional rounding"],
        [_input("raw_value", "Raw Value", "Full-precision backend value.", "decimal")],
        source_type="calculated",
        assumptions=["Currency details default to two decimals; summary metrics may use K/M abbreviations; loan interest rates display with three decimals."],
    ),
    _formula(
        "convention.annual_to_monthly", "conventions", "annual-to-monthly", "Annual to Monthly",
        "Average monthly conversion for annual amounts.",
        ["Annual Amount ÷ 12 = Average Monthly Amount"],
        [_input("annual_amount", "Annual Amount", "Backend annual amount.")],
        source_type="calculated",
        assumptions=["The result is labeled Average Monthly when it is not based on actual monthly transactions."],
        display_format="currency / month",
    ),
    _formula(
        "convention.partial_year", "conventions", "partial-year", "Partial Year",
        "How current-year and partial-year values are labeled.",
        ["YTD value through backend as-of date = Partial-year value"],
        [_input("as_of_date", "As-of Date", "Backend as-of date.", "date")],
        source_type="mixed",
        assumptions=["Current-year records display YTD · Through date. Incomplete actual YTD values are not compared with full-year projections without projected YTD normalization."],
    ),
    _formula(
        "convention.missing_values", "conventions", "missing-values", "Missing Values",
        "How missing values are displayed.",
        ["Missing value = —", "Confirmed zero = $0"],
        [_input("value", "Value", "Backend value, null, or confirmed zero.")],
        source_type="mixed",
        assumptions=["Missing values are not automatically converted to zero."],
    ),
    _formula(
        "convention.duplicate_expense_prevention", "conventions", "duplicate-expense-prevention", "Duplicate Expense Prevention",
        "Rule preventing escrow and tax or insurance disbursements from being counted twice.",
        ["Final property expense uses one resolved value per obligation and period"],
        [_input("escrow_contribution", "Escrow Contribution", "Payment mechanism."), _input("tax_or_insurance_disbursement", "Tax or Insurance Disbursement", "Final obligation payment.")],
        source_type="calculated",
        assumptions=["The backend does not count both escrow contribution and escrow-funded tax or insurance disbursement as separate final property expenses."],
    ),
]


FORMULA_AUDIT_FINDINGS: List[Dict[str, Any]] = [
    {
        "metric": "Help Center formulas",
        "currentBackendFormula": "Backend formulas are distributed across property engine, metric vault, document parsing, and property router DTO helpers.",
        "currentFrontendFormula": "Legacy HelpPage hardcoded formula text, examples, tags, and a spreadsheet export in React.",
        "expectedFormula": "Frontend renders backend formula catalog definitions from /api/help/formulas.",
        "difference": "Legacy Help page maintained duplicate formula documentation in frontend code.",
        "risk": "Formula drift between Help, tooltips, and backend engine behavior.",
        "filesAffected": ["frontend/src/pages/HelpPage.jsx", "backend/services/formula_catalog.py", "backend/routers/help.py"],
        "recommendedFix": "Use backend formula catalog as the only help-definition source.",
    },
    {
        "metric": "Summary and loan metrics",
        "currentBackendFormula": "compute_property_metrics and Metric Vault DTOs own current values; known frontend fallbacks remain in PropertyDetailPage per standards debt.",
        "currentFrontendFormula": "Some legacy components still contain fallback display math when backend-owned DTOs are unavailable.",
        "expectedFormula": "Displayed metrics use backend DTO values and stable metric keys.",
        "difference": "Known standards debt remains outside this Help Center change.",
        "risk": "Fallbacks can drift from engine values if used.",
        "filesAffected": ["frontend/src/pages/PropertyDetailPage.jsx", "frontend/src/components/LoanCard.jsx"],
        "recommendedFix": "Continue Metric Vault migration separately; do not change historical calculations in Help redesign.",
    },
    {
        "metric": "Escrow, tax, and insurance",
        "currentBackendFormula": "resolve_annual_operating_expenses and resolve_property_tax choose annual expense sources and avoid cash-flow debt-service escrow double counting.",
        "currentFrontendFormula": "Frontend renders expense and loan source badges and document controls.",
        "expectedFormula": "Formula catalog documents escrow as a payment mechanism, not a duplicate final expense.",
        "difference": "Catalog now documents the backend source-precedence rule.",
        "risk": "Without documentation users may interpret escrow as an added expense.",
        "filesAffected": ["backend/routers/properties.py", "backend/services/formula_catalog.py"],
        "recommendedFix": "Keep source precedence in backend and reuse catalog text in Help and tooltips.",
    },
    {
        "metric": "Depreciation",
        "currentBackendFormula": "Backend depreciation endpoint computes per-asset straight-line schedules, accumulated depreciation, remaining basis, and assertions.",
        "currentFrontendFormula": "Frontend depreciation tab renders backend values and chart rows.",
        "expectedFormula": "Catalog describes land exclusion, asset-specific recovery periods, partial-year convention, accumulated depreciation, and remaining basis.",
        "difference": "Catalog documentation added; no depreciation engine values changed.",
        "risk": "Low after recent backend depreciation assertion tests; basis inputs can still be missing.",
        "filesAffected": ["backend/routers/properties.py", "backend/services/formula_catalog.py"],
        "recommendedFix": "Surface backend missing-basis flags where applicable.",
    },
]


def _matches_query(formula: Dict[str, Any], query: str) -> bool:
    haystack = " ".join(
        str(part or "")
        for part in [
            formula.get("metricKey"),
            formula.get("name"),
            formula.get("shortDefinition"),
            formula.get("detailedDefinition"),
            formula.get("formula"),
            formula.get("pageKey"),
            formula.get("sectionKey"),
            " ".join(formula.get("searchTerms") or []),
            " ".join(formula.get("relatedMetricKeys") or []),
        ]
    ).lower()
    return query.lower() in haystack


def get_formula_catalog(
    *,
    page: Optional[str] = None,
    section: Optional[str] = None,
    source_type: Optional[str] = None,
    query: Optional[str] = None,
) -> Dict[str, Any]:
    formulas = FORMULA_DEFINITIONS
    if page:
        formulas = [item for item in formulas if item["pageKey"] == page]
    if section:
        formulas = [item for item in formulas if item["sectionKey"] == section]
    if source_type:
        formulas = [item for item in formulas if item["sourceType"] == source_type]
    if query:
        formulas = [item for item in formulas if _matches_query(item, query)]

    return {
        "version": CATALOG_VERSION,
        "pages": HELP_PAGES,
        "formulas": formulas,
        "audit": FORMULA_AUDIT_FINDINGS,
        "sourceTypes": ["reported", "calculated", "derived", "projected", "estimated", "manual", "mixed"],
    }
