import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import {
  HOME_TYPE_OPTIONS,
  homeTypeLabel,
  normalizeHomeType,
  propertySetupFieldPresentation,
  propertySetupFlagRows,
  propertySetupSectionIds,
  propertySetupSections,
} from './propertySetupPresentation.js'

assert.deepEqual(propertySetupSectionIds, [
  'property',
  'financing',
  'rental',
  'expenses',
])

for (const section of propertySetupSections) {
  assert.equal(Boolean(section.icon), true)
  assert.equal(Boolean(section.subtitle), true)
}

assert.deepEqual(propertySetupSections.map((section) => section.icon), [
  'Home',
  'Landmark',
  'KeyRound',
  'Receipt',
])

assert.deepEqual(propertySetupFlagRows.map((row) => row.id), [
  'hasFinancing',
  'hasHoa',
  'hasSolar',
])

for (const row of propertySetupFlagRows) {
  assert.equal(Boolean(row.icon), true)
  assert.equal(Boolean(row.helper), true)
}

assert.equal(propertySetupFieldPresentation.name.emphasis, true)
assert.equal(propertySetupFieldPresentation.purchase_price.emphasis, true)
assert.equal(propertySetupFieldPresentation.market_value.emphasis, true)
assert.equal(Boolean(propertySetupFieldPresentation.address.span), true)
assert.equal(propertySetupSections.find((section) => section.id === 'financing').title, 'Loans')
assert.deepEqual(HOME_TYPE_OPTIONS.map((option) => option.value), [
  'single_family',
  'condominium',
  'townhouse',
  'duplex',
  'triplex',
  'fourplex',
  'multi_family',
  'apartment',
  'manufactured_home',
  'mobile_home',
  'cooperative',
  'vacation_home',
  'mixed_use_property',
  'commercial_residential',
  'land',
  'other',
])
assert.equal(normalizeHomeType('Single Family'), 'single_family')
assert.equal(normalizeHomeType('single-family'), 'single_family')
assert.equal(normalizeHomeType('SFR'), 'single_family')
assert.equal(normalizeHomeType('Condo'), 'condominium')
assert.equal(normalizeHomeType('Unmapped legacy type'), 'other')
assert.equal(homeTypeLabel('single_family'), 'Single Family')
assert.equal(homeTypeLabel('other', 'Carriage House'), 'Carriage House')

const pageSource = readFileSync(new URL('../pages/PropertyFormPage.jsx', import.meta.url), 'utf8')
const detailSource = readFileSync(new URL('../pages/PropertyDetailPage.jsx', import.meta.url), 'utf8')
const loanCardSource = readFileSync(new URL('../components/LoanCard.jsx', import.meta.url), 'utf8')
const loanModalSource = readFileSync(new URL('../components/LoanModal.jsx', import.meta.url), 'utf8')
const amortizationModalSource = readFileSync(new URL('../components/AmortizationModal.jsx', import.meta.url), 'utf8')
const metricVaultSource = readFileSync(new URL('../../../backend/services/metric_vault.py', import.meta.url), 'utf8')
const backendPropertiesSource = readFileSync(new URL('../../../backend/routers/properties.py', import.meta.url), 'utf8')
const documentRouterSource = readFileSync(new URL('../../../backend/routers/documents.py', import.meta.url), 'utf8')
const rentalTabSource = detailSource.slice(
  detailSource.indexOf('function UsageTimelineTab'),
  detailSource.indexOf('function LoansTab'),
)
const scenariosTabSource = detailSource.slice(
  detailSource.indexOf('function ScenariosTab'),
  detailSource.indexOf('function ScenarioInputGroup'),
)

assert.equal(pageSource.includes('Property Setup'), true)
assert.equal(pageSource.includes('function PropertySetupSection'), true)
assert.equal(pageSource.includes('function PropertySetupTabs'), true)
assert.equal(pageSource.includes('function SetupStepIcon'), true)
assert.equal(pageSource.includes('setupStepIcons'), true)
assert.equal(pageSource.includes('role="tablist"'), true)
assert.equal(pageSource.includes('role="tab"'), true)
assert.equal(pageSource.includes('aria-selected={active}'), true)
assert.equal(pageSource.includes("state === 'complete'"), true)
assert.equal(pageSource.includes("state === 'current'"), true)
assert.equal(pageSource.includes('connectorComplete'), true)
assert.equal(pageSource.includes('rounded-full bg-green-600 text-white'), true)
assert.equal(pageSource.includes('function PropertySetupSummary'), false)
assert.equal(pageSource.includes('function PropertySetupRecords'), true)
assert.equal(pageSource.includes('function PropertySetupEditor'), true)
assert.equal(pageSource.includes('function PropertySetupFooter'), true)
assert.equal(pageSource.includes('Monthly Cash Flow Preview'), false)
assert.equal(pageSource.includes('headerCashFlow'), false)
assert.equal(pageSource.includes('This property has'), true)
assert.equal(pageSource.includes('Property Features'), false)
assert.equal(pageSource.includes('FeatureToggle'), true)
assert.equal(pageSource.includes('function SetupSubsection'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Basics">'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Purchase">'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Valuation">'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Location">'), false)
assert.equal(pageSource.includes('Purchase & Value'), false)
assert.equal(pageSource.includes('HelpCircle'), true)
assert.equal(pageSource.includes('h-11 w-full'), true)
assert.equal(pageSource.includes('h-14 w-full'), false)
assert.equal(pageSource.includes('rounded-lg border border-gray-200 bg-gray-50 p-4'), false)
assert.equal(pageSource.includes('md:grid-cols-3'), true)
assert.equal(pageSource.includes('Save Draft'), true)
assert.equal(pageSource.includes('Save Property'), true)
assert.equal(pageSource.includes('Save &amp; continue'), true)
assert.equal(pageSource.includes('Save Draft &amp; Continue'), false)
assert.equal(pageSource.includes("Choose what you'd like to do before leaving this section."), false)
assert.equal(pageSource.includes('Save them before leaving this section?'), true)
assert.equal(pageSource.includes('Discard changes'), true)
assert.equal(pageSource.includes('Stay here'), true)
assert.equal(pageSource.includes('sm:flex-row sm:items-center sm:justify-between'), true)
assert.equal(pageSource.includes('propAPI.finalizeSetup'), true)
assert.equal(pageSource.includes("navigate(payload.redirectTo || '/properties')"), true)
assert.equal(pageSource.includes('items need attention before this property can be saved.'), true)
assert.equal(pageSource.includes('Fields marked'), true)
assert.equal(pageSource.includes('REQUIRED_FIELDS'), true)
assert.equal(pageSource.includes('required={REQUIRED_FIELDS.has'), true)
assert.equal(pageSource.includes('Have your closing or settlement document?'), true)
assert.equal(pageSource.includes('Upload it to populate purchase details and loan terms.'), true)
assert.equal(pageSource.includes('or enter manually'), true)
assert.equal(pageSource.includes('handleSettlementUpload'), true)
assert.equal(pageSource.includes("category', 'closing_statement'"), true)
assert.equal(pageSource.includes('docAPI.previewUpload'), true)
assert.equal(pageSource.includes('docAPI.acceptUpload'), true)
assert.equal(pageSource.includes('docAPI.setupImportReview'), true)
assert.equal(pageSource.includes('apply_extracted: false'), true)
assert.equal(pageSource.includes('Property details found'), true)
assert.equal(pageSource.includes('Loan details found'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Loan Details">'), true)
assert.equal(pageSource.includes('<SetupSubsection title="Escrow Details">'), true)
assert.equal(pageSource.includes('Upload your latest mortgage statement to update the balance and escrow.'), true)
assert.equal(pageSource.includes('handleLoanStatementUpload'), true)
assert.equal(pageSource.includes('docAPI.loanStatementReview'), true)
assert.equal(pageSource.includes('docAPI.applyLoanStatement'), true)
assert.equal(pageSource.includes('duplicateDocumentFromError'), true)
assert.equal(pageSource.includes('loanStatementConflict'), true)
assert.equal(pageSource.includes('This mortgage statement is already uploaded.'), true)
assert.equal(pageSource.includes('Review existing'), true)
assert.equal(pageSource.includes('Open Documents'), true)
assert.equal(pageSource.includes('Choose another file'), true)
assert.equal(pageSource.includes("category', 'mortgage_statement'"), true)
assert.equal(pageSource.includes('Mortgage statement values found'), true)
assert.equal(pageSource.includes('from statement'), true)
assert.equal(pageSource.includes('Reported from mortgage statement'), true)
assert.equal(pageSource.includes('mortgage_statement_reported_balance'), true)
assert.equal(pageSource.includes('Statement date'), true)
assert.equal(pageSource.includes('Escrow included'), true)
assert.equal(pageSource.includes('Monthly property tax escrow'), true)
assert.equal(pageSource.includes('Monthly insurance escrow'), true)
assert.equal(pageSource.includes('Monthly mortgage insurance'), true)
assert.equal(pageSource.includes('Other monthly escrow'), true)
assert.equal(pageSource.includes('Total monthly escrow'), true)
assert.equal(pageSource.includes('Estimated total monthly payment'), true)
assert.equal(pageSource.includes('Extra Monthly Payment'), false)
assert.equal(pageSource.includes('+ toNumber(loan.monthly_property_tax_escrow)'), false)
assert.equal(pageSource.includes('Apply selected values'), true)
assert.equal(pageSource.includes('Keep current values'), true)
assert.equal(pageSource.includes('Linked document'), true)
assert.equal(pageSource.includes('Review import'), true)
assert.equal(pageSource.includes('Delink this document?'), true)
assert.equal(pageSource.includes('Delink Document'), true)
assert.equal(pageSource.includes('settlementSourcesFromDocument'), true)
assert.equal(pageSource.includes('from settlement'), true)
assert.equal(pageSource.includes('formatCurrency(toNumber(value))'), true)
assert.equal(pageSource.includes('Original Residency Status'), true)
assert.equal(pageSource.includes('Current Residency Status'), true)
assert.equal(pageSource.includes('How the property was originally acquired or first used.'), true)
assert.equal(pageSource.includes('How the property is being used today.'), true)
assert.equal(pageSource.includes('RESIDENCY_OPTIONS'), true)
assert.equal(pageSource.includes('originalResidencyFromUsage'), true)
assert.equal(pageSource.includes('rental_start_date_origin'), true)
assert.equal(pageSource.includes('Defaulted from purchase date'), true)
assert.equal(pageSource.includes('Rental availability cannot begin before the property was purchased.'), true)
assert.equal(pageSource.includes('annualExpenseSourceBadge'), true)
assert.equal(pageSource.includes('Estimated (escrow)'), true)
assert.equal(pageSource.includes('property_tax_source'), true)
assert.equal(pageSource.includes('insurance_source'), true)
assert.equal(pageSource.includes('expenseEstimates'), true)
assert.equal(pageSource.includes('monthlyPropertyTaxEscrow * 12'), false)
assert.equal(pageSource.includes('monthlyInsuranceEscrow * 12'), false)
assert.equal(pageSource.includes('HOME_TYPE_OPTIONS'), true)
assert.equal(pageSource.includes('label="Home Type"'), true)
assert.equal(pageSource.includes('<TextInput label="Type"'), false)
assert.equal(pageSource.includes('The physical type of property.'), true)
assert.equal(pageSource.includes('Other Home Type'), true)
assert.equal(pageSource.includes('property_type_raw'), true)
assert.equal(pageSource.includes('valuationDateOrigin'), true)
assert.equal(pageSource.includes("'user_entered'"), true)
assert.equal(pageSource.includes("setValuationDateOrigin('imported_document')"), true)
assert.equal(pageSource.includes('Valuation date cannot be earlier than purchase date.'), true)
assert.equal(pageSource.includes('The date associated with the current market value. It initially defaults to the purchase date and can be updated.'), true)
assert.equal(pageSource.includes('docAPI.uploadExpenseField'), true)
assert.equal(pageSource.includes('expenseAddressReview'), true)
assert.equal(pageSource.includes('docAPI.applyExpenseFieldDocument'), true)
assert.equal(pageSource.includes('docAPI.removeExpenseFieldDocument'), true)
assert.equal(pageSource.includes('`${field.key}_document`'), true)
assert.equal(pageSource.includes('btn-secondary mt-6'), false)
assert.equal(pageSource.includes('Replace'), true)
assert.equal(pageSource.includes('Address mismatch'), true)
assert.equal(pageSource.includes('Same address — accept'), true)
assert.equal(pageSource.includes('Wrong document — remove'), true)
assert.equal(pageSource.includes('Address confirmed'), true)
assert.equal(pageSource.includes('doc — PDF, xls'), true)
assert.equal(documentRouterSource.includes('_expense_address_requires_review'), true)
assert.equal(documentRouterSource.includes('apply-expense-field-document'), true)
assert.equal(documentRouterSource.includes('addressOverride'), true)
assert.equal(documentRouterSource.includes('format_percent(score * 100)'), true)
assert.equal(rentalTabSource.includes('timeline?.storyLead'), true)
assert.equal(rentalTabSource.includes('timeline?.heroKpis'), true)
assert.equal(rentalTabSource.includes('timeline?.insightLine'), true)
assert.equal(rentalTabSource.includes('timelineFormOpen'), true)
assert.equal(rentalTabSource.includes('h-2.5 w-2.5 rounded-full'), true)
assert.equal(rentalTabSource.includes('grid w-full grid-cols-12 overflow-hidden'), true)
assert.equal(rentalTabSource.includes('grid grid-cols-[56px_minmax(0,1fr)]'), false)
assert.equal(rentalTabSource.includes("grid-cols-[minmax(360px,0.48fr)_minmax(0,0.52fr)]"), true)
assert.equal(rentalTabSource.includes('Received'), true)
assert.equal(rentalTabSource.includes('Expected'), true)
assert.equal(rentalTabSource.includes('expectedRentDisplay'), true)
assert.equal(rentalTabSource.includes("['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']"), true)
assert.equal(rentalTabSource.includes('monthTooltipText'), true)
assert.equal(rentalTabSource.includes('min-w-[360px]'), false)
assert.equal(rentalTabSource.includes('overflow-x-auto'), false)
assert.equal(rentalTabSource.includes('aria-label={ariaLabel || tooltip}'), true)
assert.equal(rentalTabSource.includes('startAddTimelinePeriod({ startDate: month.startDate, endDate: month.endDate })'), true)
assert.equal(rentalTabSource.includes('Yearly Performance'), false)
assert.equal(rentalTabSource.includes('Rental Insights'), false)
assert.equal(rentalTabSource.includes('Recommendations'), false)
assert.equal(scenariosTabSource.includes('xl:grid-cols-[minmax(0,1fr)_260px]'), true)
assert.equal(scenariosTabSource.includes('max-h-[calc(100vh-10rem)] overflow-y-auto'), true)
assert.equal(scenariosTabSource.includes('ScenarioControlGroup title="Payoff"'), true)
assert.equal(scenariosTabSource.includes('ScenarioControlGroup title="Compare vs investing"'), true)
assert.equal(scenariosTabSource.includes('label="Extra/mo"'), true)
assert.equal(scenariosTabSource.includes('Save as scenario'), true)
assert.equal(scenariosTabSource.includes('hidden mt-4'), false)
assert.equal(scenariosTabSource.includes('Enable this strategy type to include it.'), false)
assert.equal(scenariosTabSource.includes('Expected Investment Return'), false)
assert.equal(detailSource.includes('PROPERTY_TAB_METRICS'), true)
assert.equal(detailSource.includes('Market Value\" metric'), false)
assert.equal(detailSource.includes('Value {metricDisplayText(headerMarketValue)} · Equity {metricDisplayText(headerEquity)}'), true)
assert.equal(detailSource.includes("label: 'Total loan', key: 'loanTotalOriginal'"), true)
assert.equal(detailSource.includes("label: 'Interest', key: 'loanInterestRateSummary'"), true)
assert.equal(detailSource.includes('Paid to date'), true)
assert.equal(detailSource.includes('Loan count'), false)
assert.equal(detailSource.includes('loanPrincipalPaidToDate'), true)
assert.equal(detailSource.includes('loanBlendedRate'), false)
assert.equal(detailSource.includes('Blended rate'), false)
assert.equal(metricVaultSource.includes('"loanTotalOriginal"'), true)
assert.equal(metricVaultSource.includes('"loanInterestRateSummary"'), true)
assert.equal(metricVaultSource.includes('"balanceCheck"'), true)
assert.equal(loanCardSource.includes('title="Upload statement"'), true)
assert.equal(loanCardSource.includes('title="Edit"'), true)
assert.equal(loanCardSource.includes('title="Close loan"'), true)
assert.equal(loanCardSource.includes('title="Delete"'), true)
assert.equal(loanCardSource.includes('Paid {principalPaid}'), true)
assert.equal(loanCardSource.includes('computedPayment'), false)
assert.equal(loanCardSource.includes('MiniAmortizationChart'), false)
assert.equal(loanModalSource.includes('Upload loan statement'), true)
assert.equal(amortizationModalSource.includes('Payoff comparison'), true)
assert.equal(amortizationModalSource.includes('Extra / mo'), true)
assert.equal(amortizationModalSource.includes('regularBalance'), true)
assert.equal(amortizationModalSource.includes('extraBalance'), true)
assert.equal(amortizationModalSource.includes('strokeDasharray="6 4"'), true)
assert.equal(amortizationModalSource.includes('Cumulative interest'), false)
assert.equal(metricVaultSource.includes('loanPrincipalPaidToDate'), true)
assert.equal(metricVaultSource.includes('loanBlendedRate'), false)
assert.equal(backendPropertiesSource.includes('payoffComparison'), true)
assert.equal(backendPropertiesSource.includes('_loan_payoff_comparison'), true)
assert.equal(pageSource.includes('of {setupProgress.total} sections complete'), true)
assert.equal(pageSource.includes('fixed inset-x-0 bottom-0'), false)
assert.equal(pageSource.includes('saveSection(activeSection, true)'), false)
assert.equal(pageSource.includes('<aside'), false)
assert.equal(pageSource.includes('setup-section-selector'), false)
assert.equal(pageSource.includes('sticky top-0 z-30 bg-white/95'), true)
assert.equal(pageSource.includes('<header className="sticky top-0'), false)
assert.equal(pageSource.includes('aria-label="Property form sections"'), true)
assert.equal(pageSource.includes('tabs={('), true)
assert.equal(pageSource.includes('summaryItems='), false)
assert.equal(pageSource.includes("id: 'depreciation'"), false)
assert.equal(pageSource.includes("id: 'tax-records'"), false)
assert.equal(pageSource.includes("sectionId === 'depreciation'"), false)
assert.equal(pageSource.includes("sectionId === 'tax-records'"), false)
assert.equal(pageSource.includes('propAPI.depreciation'), false)
assert.equal(pageSource.includes('propAPI.taxEntries'), false)
assert.equal(pageSource.includes('renderDepreciation'), false)
assert.equal(pageSource.includes('renderTax'), false)
assert.equal(pageSource.includes('No tax records.'), false)
assert.equal(pageSource.includes('Import Schedule E'), false)
assert.equal(pageSource.includes('When it opened as a rental'), true)
assert.equal(pageSource.includes('Rental availability is separate from occupancy.'), true)
assert.equal(pageSource.includes('Current status'), false)
assert.equal(pageSource.includes('+ Add occupied period'), true)
assert.equal(pageSource.includes('Occupancy log'), true)
assert.equal(pageSource.includes('Existing Loans'), true)
assert.equal(pageSource.includes('Edit Loan'), true)
assert.equal(pageSource.includes('Assets'), false)
assert.equal(pageSource.includes('Add Improvement'), false)
assert.equal(pageSource.includes('Recorded Tax Years'), false)
assert.equal(pageSource.includes('Add Tax Record'), false)
assert.equal(pageSource.includes('Vacancy rows are calculated automatically from the gaps.'), true)
assert.equal(pageSource.includes('Delete occupancy period?'), true)
assert.equal(pageSource.includes('Initial balance from closing document'), true)
assert.equal(pageSource.includes('current_balance_source_label'), true)
assert.equal(pageSource.includes('importStatusLabel'), true)
assert.equal(pageSource.includes('EXPENSE_FIELDS'), true)
assert.equal(pageSource.includes("Property tax / yr"), true)
assert.equal(pageSource.includes("Insurance / yr"), true)
assert.equal(pageSource.includes("HOA / yr"), true)
assert.equal(pageSource.includes("Repairs and maintenance / yr"), true)
assert.equal(pageSource.includes("Property management / yr"), true)
assert.equal(pageSource.includes("Utilities / yr"), true)
assert.equal(pageSource.includes("Vacancy allowance / yr"), true)
assert.equal(pageSource.includes("CapEx reserve / yr"), true)
assert.equal(pageSource.includes("Other / yr"), true)
assert.equal(pageSource.includes("HOA special assessment / yr"), true)
assert.equal(pageSource.includes('Copy prior year'), true)
assert.equal(pageSource.includes('View all years'), false)
assert.equal(pageSource.includes('Current Year Summary'), true)
assert.equal(pageSource.includes('renderExpenseHistoryRecords'), true)
assert.equal(pageSource.includes('Edit ${expenseYear} Expenses'), true)
assert.equal(pageSource.includes('propAPI.annualExpenses'), true)
assert.equal(pageSource.includes('propAPI.upsertAnnualExpense'), true)
assert.equal(pageSource.includes('annual_expenses: currentExpenseRowsForSave()'), true)
assert.equal(pageSource.includes('No annual expense years available.'), true)
assert.equal(pageSource.includes('Blank years are not assumed to be $0.'), true)
assert.equal(pageSource.includes('HOA / mo'), false)
assert.equal(pageSource.includes('Repairs and maintenance / mo'), false)
assert.equal(pageSource.includes('Property management / mo'), false)
assert.equal(pageSource.includes('Utilities / mo'), false)
assert.equal(pageSource.includes('Vacancy allowance / mo'), false)
assert.equal(pageSource.includes('CapEx reserve / mo'), false)
assert.equal(pageSource.includes('Other expenses / mo'), false)
assert.equal(pageSource.includes('PercentInput label="Occupancy rate"'), false)
assert.equal(pageSource.includes("['Occupancy %'"), false)
assert.equal(pageSource.includes("['Vacancy %'"), false)
assert.ok(pageSource.indexOf('<main') < pageSource.indexOf('<PropertySetupTabs'))
assert.ok(pageSource.indexOf('<PropertySetupTabs') < pageSource.indexOf('activePresentation={activePresentation}'))
assert.ok(pageSource.indexOf('records={renderSectionRecords(activeSection)}') < pageSource.indexOf('editor={renderSectionEditor(activeSection)}'))
assert.ok(pageSource.indexOf('editor={renderSectionEditor(activeSection)}') < pageSource.indexOf('footer={('))
